---
- name: Install libvirt and QEMU packages
  ansible.builtin.apt:
    name: "{{ libvirt_packages }}"
    state: present
    update_cache: true

- name: Enable and start libvirtd
  ansible.builtin.service:
    name: "{{ libvirt_service }}"
    state: started
    enabled: true

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ libvirt_user }}"
    groups: libvirt
    append: true
  notify: Reset connection
