set shell := ["bash", "-c"]
set dotenv-path := "../setup.env"
set dotenv-load
set dotenv-required := false

mod ubuntu "ubuntu/justfile"
mod talos "talos/justfile"

[private]
default:
    @just --list
